@baseUrl = http://localhost:3000

### Faz o login
# @name login
POST {{baseUrl}}/admin/login 
Content-Type: application/json

{
    "password": "29012024"
    
}

### Pegar todos os grupos de um evento
@token = {{login.response.body.token}}
GET {{baseUrl}}/admin/events/1/groups
Content-Type: application/json
Authorization: Bearer {{token}}

### Pegar um grupo de um evento
GET {{baseUrl}}/admin/events/1/groups/2
Content-Type: application/json
Authorization: Bearer {{token}}

### Criar um grupo em um evento
POST {{baseUrl}}/admin/events/1/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Group teste"
}

### Update group
PUT {{baseUrl}}/admin/events/1/groups/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Testando o update"
}

### Deletar grupo do evento
DELETE {{baseUrl}}/admin/events/1/groups/3
Content-Type: application/json
Authorization: Bearer {{token}}